module Tables where
import AST (Args (..),Type(..),TableDescript(..),RefOption(..))
import Data.Typeable
import Data.HashMap.Strict hiding (keys)
import Avl
import COrdering
keys = ["owner","dataBase","tableName"]
upd0 = E
upd1 = m keys upd0 (Z (Z (Z E (fromList [("types",TT [Int,Int]),("fkey",TFK [("Persona",[("codigo","codigo")]),("Persona",[("vendedor","codigo")])]),("refBy",TR [("Visitas",Cascades,Cascades)]),("key",TK ["codigo"]),("dataBase",TB "Inmobiliaria"),("tableName",TN "Cliente"),("haveNull",HN []),("scheme",TS ["codigo","vendedor"]),("owner",TO "pablo")]) E) (fromList [("types",TT [String,Int,String,Int,String,String]),("fkey",TFK [("Zona",[("nombreP","nombrePoblacion"),("nombreZ","nombreZona")])]),("refBy",TR [("Visitas",Cascades,Cascades)]),("key",TK ["codigo"]),("dataBase",TB "Inmobiliaria"),("tableName",TN "Inmueble"),("haveNull",HN []),("scheme",TS ["codigo","precio","direccion","superficie","nombreP","nombreZ"]),("owner",TO "pablo")]) (Z E (fromList [("types",TT [Int,String,String,String,Int]),("fkey",TFK []),("refBy",TR [("Cliente",Cascades,Cascades),("Cliente",Cascades,Cascades),("Vendedor",Cascades,Cascades)]),("key",TK ["codigo"]),("dataBase",TB "Inmobiliaria"),("tableName",TN "Persona"),("haveNull",HN ["domicilio","telefono"]),("scheme",TS ["codigo","nombre","apellido","domicilio","telefono"]),("owner",TO "pablo")]) E)) (fromList [("types",TT [String,Int]),("fkey",TFK []),("refBy",TR [("Zona",Cascades,Cascades)]),("key",TK ["nombrePoblacion"]),("dataBase",TB "Inmobiliaria"),("tableName",TN "Poblacion"),("haveNull",HN ["nHabitantes"]),("scheme",TS ["nombrePoblacion","nHabitantes"]),("owner",TO "pablo")]) (N E (fromList [("types",TT [Int,String,Int]),("fkey",TFK [("Persona",[("codigo","codigo")])]),("refBy",TR []),("key",TK ["codigo"]),("dataBase",TB "Inmobiliaria"),("tableName",TN "Vendedor"),("haveNull",HN ["cuil","sueldo"]),("scheme",TS ["codigo","cuil","sueldo"]),("owner",TO "pablo")]) (Z E (fromList [("types",TT [String,String]),("fkey",TFK [("Poblacion",[("nombrePoblacion","nombrePoblacion")])]),("refBy",TR [("Inmueble",Cascades,Cascades)]),("key",TK ["nombreZona","nombrePoblacion"]),("dataBase",TB "Inmobiliaria"),("tableName",TN "Zona"),("haveNull",HN []),("scheme",TS ["nombrePoblacion","nombreZona"]),("owner",TO "pablo")]) E)))

upd2 = m keys upd1 (Z E (fromList [("types",TT [Int,String,Datetime]),("fkey",TFK [("Cliente",[("codigoCliente","codigo")]),("Inmueble",[("codigoInmueble","codigo")])]),("refBy",TR []),("key",TK ["codigoInmueble","fechaHora"]),("dataBase",TB "Inmobiliaria"),("tableName",TN "Visitas"),("haveNull",HN []),("scheme",TS ["codigoCliente","codigoInmueble","fechaHora"]),("owner",TO "pablo")]) E)